Revert "techpack: audio: Make all drivers built in"
This reverts commit 5a81c622ce9e0753f0c300af85dffe0d8a28854f.

Android is getting bigger and bigger through the years: we have now
reached the point of not being able to fit the kernel inside of certain
boot partitions:

  error: +out/target/product/bahamut/boot.img too large (67108864 > 67039232)

Move techpack/audio to modules again to free up some space.

Signed-off-by: voidanix <voidanix@keyedlimepie.org>