ANDROID: mm: multi-gen LRU: Depend on DEBUG_FS
Enable DEBUG_FS when using MGLRU as this feature depends on it:

  ../../../../../../kernel/sony/sm8150/mm/vmscan.c:4784:15: error: implicit declaration of function 'debugfs_real_fops' [-Werror,-Wimplicit-function-declaration]
   4784 |         bool full = !debugfs_real_fops(m->file)->write;
        |                      ^
  ../../../../../../kernel/sony/sm8150/mm/vmscan.c:4784:43: error: member reference type 'int' is not a pointer
   4784 |         bool full = !debugfs_real_fops(m->file)->write;
        |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
  2 errors generated.

Strangely enough, Android 12/13 VSRs want DEBUG_FS=n, but newer versions
of Android want DEBUG_FS=y as vendors do indeed use it. On the other
hand, due to MGLRU, this feature is also now a requirement.

Link: https://android-review.googlesource.com/c/kernel/configs/+/3308756/1#message-05220f8c2c8a38e8c871d820db70ba2daecfde4b
Signed-off-by: voidanix <voidanix@keyedlimepie.org>